"""Training pipeline for baseline win-probability models."""

from __future__ import annotations

import json
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any

import joblib
import numpy as np
import pandas as pd
from sklearn.ensemble import HistGradientBoostingClassifier, RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, log_loss, roc_auc_score
from sklearn.model_selection import TimeSeriesSplit
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler


@dataclass(frozen=True)
class ModelMetrics:
    """Evaluation metrics for one model."""

    name: str
    cv_accuracy: float
    cv_roc_auc: float
    test_accuracy: float
    test_roc_auc: float
    test_log_loss: float
    folds: int


@dataclass(frozen=True)
class TrainingSummary:
    """Result of a training run."""

    best_model: str
    artifact_path: str
    metrics_path: str
    metrics: list[ModelMetrics]
    train_rows: int
    test_rows: int
    features: int


def load_feature_matrices(feature_dir: str | Path) -> tuple[pd.DataFrame, pd.Series, pd.DataFrame, pd.Series]:
    """Load feature matrix CSV files generated by scripts/build_features.py."""

    directory = Path(feature_dir)
    paths = {
        "X_train": directory / "X_train.csv",
        "X_test": directory / "X_test.csv",
        "y_train": directory / "y_train.csv",
        "y_test": directory / "y_test.csv",
    }
    missing = [name for name, path in paths.items() if not path.exists()]
    if missing:
        raise FileNotFoundError(f"missing feature files in {directory}: {missing}")
    x_train = pd.read_csv(paths["X_train"])
    x_test = pd.read_csv(paths["X_test"])
    y_train = pd.read_csv(paths["y_train"]).iloc[:, 0].astype(int)
    y_test = pd.read_csv(paths["y_test"]).iloc[:, 0].astype(int)
    if x_train.empty or x_test.empty:
        raise ValueError("train and test feature matrices must both contain rows")
    return x_train, y_train, x_test, y_test


def load_feature_metadata(feature_dir: str | Path) -> dict[str, Any]:
    """Load optional feature build metadata such as category maps."""

    path = Path(feature_dir) / "feature_metadata.json"
    if not path.exists():
        return {}
    return json.loads(path.read_text(encoding="utf-8"))


def candidate_models() -> dict[str, Any]:
    """Return available classifiers for win-probability training."""

    models: dict[str, Any] = {
        "logistic_regression": Pipeline(
            steps=[
                ("scaler", StandardScaler()),
                ("model", LogisticRegression(max_iter=1000, class_weight="balanced")),
            ]
        ),
        "random_forest": RandomForestClassifier(
            n_estimators=180,
            min_samples_leaf=2,
            class_weight="balanced_subsample",
            random_state=42,
            n_jobs=-1,
        ),
        "hist_gradient_boosting": HistGradientBoostingClassifier(
            max_iter=120,
            learning_rate=0.06,
            max_leaf_nodes=31,
            l2_regularization=0.05,
            random_state=42,
        ),
    }
    try:
        from xgboost import XGBClassifier

        models["xgboost"] = XGBClassifier(
            n_estimators=220,
            max_depth=4,
            learning_rate=0.045,
            subsample=0.9,
            colsample_bytree=0.9,
            eval_metric="logloss",
            random_state=42,
            n_jobs=-1,
        )
    except ImportError:
        pass
    try:
        from lightgbm import LGBMClassifier

        models["lightgbm"] = LGBMClassifier(
            n_estimators=260,
            learning_rate=0.04,
            num_leaves=31,
            random_state=42,
            verbose=-1,
        )
    except ImportError:
        pass
    return models


def _safe_roc_auc(y_true: pd.Series, probabilities: np.ndarray) -> float:
    if len(set(y_true)) < 2:
        return 0.0
    return float(roc_auc_score(y_true, probabilities))


def _safe_log_loss(y_true: pd.Series, probabilities: np.ndarray) -> float:
    labels = [0, 1]
    return float(log_loss(y_true, probabilities, labels=labels))


def _probabilities(model: Any, features: pd.DataFrame) -> np.ndarray:
    if not hasattr(model, "predict_proba"):
        raise RuntimeError(f"{type(model).__name__} does not expose predict_proba")
    return model.predict_proba(features)[:, 1]


def backtest_model(name: str, model: Any, features: pd.DataFrame, target: pd.Series, folds: int = 5) -> tuple[float, float]:
    """Evaluate model using TimeSeriesSplit only."""

    if folds < 2:
        raise ValueError("folds must be at least 2")
    if len(features) <= folds + 1:
        folds = max(2, len(features) - 2)
    splitter = TimeSeriesSplit(n_splits=folds)
    accuracies: list[float] = []
    aucs: list[float] = []
    for train_idx, validation_idx in splitter.split(features):
        fold_model = candidate_models()[name]
        fold_model.fit(features.iloc[train_idx], target.iloc[train_idx])
        probabilities = _probabilities(fold_model, features.iloc[validation_idx])
        predictions = (probabilities >= 0.5).astype(int)
        accuracies.append(float(accuracy_score(target.iloc[validation_idx], predictions)))
        aucs.append(_safe_roc_auc(target.iloc[validation_idx], probabilities))
    return round(float(np.mean(accuracies)), 4), round(float(np.mean(aucs)), 4)


def train_baselines(
    feature_dir: str | Path = "data/features",
    artifact_dir: str | Path = "artifacts/models",
    folds: int = 5,
) -> TrainingSummary:
    """Train baseline win-probability models and persist the best one."""

    x_train, y_train, x_test, y_test = load_feature_matrices(feature_dir)
    feature_metadata = load_feature_metadata(feature_dir)
    models = candidate_models()
    metrics: list[ModelMetrics] = []
    fitted_models: dict[str, Any] = {}

    for name, model in models.items():
        actual_folds = min(folds, max(2, len(x_train) - 2))
        cv_accuracy, cv_auc = backtest_model(name, model, x_train, y_train, actual_folds)
        model.fit(x_train, y_train)
        probabilities = _probabilities(model, x_test)
        predictions = (probabilities >= 0.5).astype(int)
        metrics.append(
            ModelMetrics(
                name=name,
                cv_accuracy=cv_accuracy,
                cv_roc_auc=cv_auc,
                test_accuracy=round(float(accuracy_score(y_test, predictions)), 4),
                test_roc_auc=round(_safe_roc_auc(y_test, probabilities), 4),
                test_log_loss=round(_safe_log_loss(y_test, probabilities), 4),
                folds=actual_folds,
            )
        )
        fitted_models[name] = model

    best = max(metrics, key=lambda item: (item.test_roc_auc, item.test_accuracy, item.cv_roc_auc))
    artifact_output = Path(artifact_dir)
    artifact_output.mkdir(parents=True, exist_ok=True)
    artifact_path = artifact_output / "win_probability_baseline.joblib"
    metrics_path = artifact_output / "training_metrics.json"
    joblib.dump(
        {
            "model": fitted_models[best.name],
            "model_name": best.name,
            "feature_columns": list(x_train.columns),
            "feature_defaults": x_train.mean(numeric_only=True).to_dict(),
            "category_maps": feature_metadata.get("category_maps", {}),
            "metrics": asdict(best),
        },
        artifact_path,
    )
    metrics_path.write_text(
        json.dumps(
            {
                "best_model": best.name,
                "train_rows": len(x_train),
                "test_rows": len(x_test),
                "features": len(x_train.columns),
                "metrics": [asdict(metric) for metric in metrics],
            },
            indent=2,
        ),
        encoding="utf-8",
    )
    return TrainingSummary(
        best_model=best.name,
        artifact_path=str(artifact_path),
        metrics_path=str(metrics_path),
        metrics=metrics,
        train_rows=len(x_train),
        test_rows=len(x_test),
        features=len(x_train.columns),
    )
